<?php
/**
 * Copyright © 2015 Webwolk. All rights reserved.
 * See LICENSE for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
<h1 class="logo">
<?php if (!$block->isHomePage()):?>
    <a href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
<?php endif ?>
    <span><?php echo $storeName ?></span>
<?php if (!$block->isHomePage()):?>
    </a>
<?php endif?>
</h1>
