<?php
/**
 * Copyright © 2015 Webwolk. All rights reserved.
 * See LICENSE for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0 level-top parent"><a href="/voetverzorging/" class="level-top"><span>Voetverzorging</span></a>
            <ul class="level0 submenu">
                <li class="level1"><a href="/tegemoetkoming/"><span>Tegemoetkoming</span></a></li>
            </ul>
        </li>
        <li class="level0"><a href="/voetreflexologie/" class="level-top"><span>Voetreflexologie</span></a></li>
        <?php echo $_menu; ?>
        <li class="level0"><a href="/over-mezelf/" class="level-top"><span>Over mezelf</span></a></li>
        <li class="level0"><a href="/memory-spel/" class="level-top"><span>Spelletje</span></a></li>
        <li class="level0"><a href="/contact/" class="level-top"><span>Contact</span></a></li>
     </ul>
</nav>




