<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile


?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0"><a href="/aanbod" class="level-top">Aanbod</a></li>
        <li class="level0"><a href="/tegemoetkoming" class="level-top">Tegemoetkoming</a></li>
        <?php echo $_menu; ?>
        <li class="level0"><a href="/memory-spel" class="level-top">Spelletje</a></li>
        <li class="level0"><a href="/about-me" class="level-top">Over mezelf</a></li>
        <li class="level0"><a href="/contact" class="level-top">Contact</a></li>
     </ul>
</nav>
