<?php
/**
 * Copyright © 2015 Webwolk. All rights reserved.
 * See LICENSE for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="kotn">
<div>

<form class="form contact"
      action="<?php echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo __('Write Us') ?></span></legend><br />
        <div class="field note no-label"><?php echo __('Jot us a note and we’ll get back to you as quickly as possible.') ?></div>
        <div class="field name required">
            <label class="label" for="name"><span><?php echo __('Name') ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?php echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?php echo __('Email') ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field address required">
            <label class="label" for="address"><span><?php echo __('Street and number') ?></span></label>
            <div class="control">
                <input name="address" id="address" title="<?php echo __('Street and number') ?>" value="" class="input-text" type="text" data-validate="{required:true}" />
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city"><span><?php echo __('Zip and city') ?></span></label>
            <div class="control">
                <input name="city" id="city" title="<?php echo __('Zip and city') ?>" value="" class="input-text" type="text" data-validate="{required:true}" />
            </div>
        </div>
        <div class="field telephone required">
            <label class="label" for="telephone"><span><?php echo __('Phone Number') ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?php echo __('Phone Number') ?>" value="" class="input-text" type="text" data-validate="{required:true}" />
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?php echo __('What’s on your mind?') ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?php echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary">
                <span><?php echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>

</div>
<!-- split kotn -->
<div>

<h3>Contact info</h3>

<div itemscope itemtype="http://schema.org/HealthAndBeautyBusiness">
    <div><strong itemprop="name">Pedicure Pecceu</strong></div>
    <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
        <span itemprop="streetAddress">Kanunnik Dokter Louis Colensstraat 11</span><br />
        <span itemprop="postalCode">8400</span> <span itemprop="addressLocality">Oostende</span>
    </div>
    Telefoon: <a href="tel:0032495131225" itemprop="telephone">0495/13.12.25</a><br />
    E-mail: <span><script>document.write('<'+'a'+' '+'h'+'r'+'e'+'f'+'='+"'"+'m'+'a'+'&'+'#'+'1'+'0'+'5'+';'+'l'+'t'+'&'+'#'+'1'+'1'+'1'+';'+'&'+'#'+'5'+'8'+';'+'p'+'&'+'#'+'3'+'7'+';'+'6'+'&'+'#'+'5'+'3'+';'+'&'+'#'+'1'+'0'+'0'+';'+'i'+'c'+'&'+'#'+'1'+'1'+'7'+';'+'r'+'&'+'#'+'1'+'0'+'1'+';'+'&'+'#'+'4'+'6'+';'+'&'+'#'+'1'+'1'+'2'+';'+'&'+'#'+'1'+'0'+'1'+';'+'c'+'%'+'6'+'3'+'&'+'#'+'1'+'0'+'1'+';'+'&'+'#'+'1'+'1'+'7'+';'+'&'+'#'+'6'+'4'+';'+'l'+'&'+'#'+'1'+'0'+'5'+';'+'&'+'#'+'1'+'1'+'8'+';'+'&'+'#'+'1'+'0'+'1'+';'+'%'+'2'+'E'+'c'+'%'+'6'+'F'+'&'+'#'+'3'+'7'+';'+'6'+'&'+'#'+'6'+'8'+';'+"'"+'>'+'p'+'e'+'d'+'i'+'c'+'u'+'&'+'#'+'1'+'1'+'4'+';'+'e'+'&'+'#'+'4'+'6'+';'+'&'+'#'+'1'+'1'+'2'+';'+'&'+'#'+'1'+'0'+'1'+';'+'c'+'c'+'&'+'#'+'1'+'0'+'1'+';'+'&'+'#'+'1'+'1'+'7'+';'+'&'+'#'+'6'+'4'+';'+'l'+'i'+'v'+'e'+'&'+'#'+'4'+'6'+';'+'c'+'o'+'m'+'<'+'/'+'a'+'>');</script></span>
</div>
<p>&nbsp;</p>

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1014.7350765585716!2d2.916219096219336!3d51.22699965059353!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xdc043659f5a091c5!2sPedicure+Pecceu!5e0!3m2!1snl!2sus!4v1450128164090" width="100%" height="360" frameborder="0" style="border:0" allowfullscreen></iframe>

</div>
</div>
